// model that contains the information that the DML-ES application would
// need to know about a logged-in user's currently chosen profile

// this is a read-only model - it is a reflection of what is known about the user
// generated by the BT from the userProfile database info
// any updates would be done to the UserProfile object not the CurrentUserProfile object

export class CurrentUserProfile {

    public id: any = null;
    public profileName: string = "";
    public pkiDn: string = "";
    public dodaac: string = "";
    public email: string = "";
    public firstName: string = "";
    public lastName: string = "";
    public userType: string = "";
    public serviceCode: string = "";
    public regionCode: string = "";
    public active: Boolean = true;
    public states: Array<string> = [];
    public elements: Array<string> = [];
    public phoneNumbers: Array<any> = [];

    /**
    public userProfileType: string = "";
    public service: any = null;
    public region: any = null;
    public roles: Array<any> = [];
    public assignedPermissions: Array<any> = [];
     **/

    constructor();
    constructor(obj: CurrentUserProfile);
    constructor(obj?: any) {
        this.id = obj && obj.id || null;
        this.profileName = obj && obj.profileName || "";
        this.pkiDn = obj && obj.pkiDn || "";
        this.dodaac = obj && obj.dodaac || "";
        this.email = obj && obj.email || "";
        this.firstName = obj && obj.firstName || "";
        this.lastName = obj && obj.lastName || "";
        this.userType = obj && obj.userType || "";
        this.serviceCode = obj && obj.serviceCode || "";
        this.regionCode = obj && obj.regionCode || "";
        this.active = obj && obj.active || true;
        this.states = obj && obj.states || [];
        this.elements = obj && obj.elements || [];
        this.phoneNumbers = obj && obj.phoneNumbers || [];

        /**
        this.userProfileType = obj && obj.userProfileType || "";
        this.service = obj && obj.service || null;
        this.region = obj && obj.region || null;
        this.roles = obj && obj.roles || [];
        this.assignedPermissions = obj && obj.assignedPermissions || [];
         **/
    };
}
